# Generated by Django 6.1 on 2026-08-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paystack_ref_alter_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paystack_ref',
        ),
    ]
