# Generated by Django 6.1 on 2026-08-14 19:11

from django.db import migrations, models
from django.utils import timezone


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    prefix = f"ORD-{timezone.now().year}-"
    used_numbers = set(
        Order.objects.filter(order_number__startswith=prefix).values_list(
            "order_number", flat=True
        )
    )

    for order in Order.objects.order_by("id"):
        if order.order_number:
            continue

        seq = 1
        while f"{prefix}{seq:04d}" in used_numbers:
            seq += 1

        order.order_number = f"{prefix}{seq:04d}"
        used_numbers.add(order.order_number)
        order.save(update_fields=["order_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_paystack_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.RunPython(
            populate_order_numbers, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
